### ISSUE TITLE
'Homelink in Range' Driver shows False

### ISSUE THREAD

**Issue by tritip** [Panda88CO/udi-TeslaEV#5]
HomeLink in Range is **False** even though the car is parked in the garage... 

Thanks again, assuming it isn't a user error.  The debug shows the Json response for 'homelink_nearby' is True.

Update:  The status node flips to  **True** when the vechicle is **out** of range.

**Comment by Panda88CO** [comment]
I may have logic swapped - I'll take a look - I have no real way to test this and replying on people to help me :-)

**Comment by Panda88CO** [comment]
i had true and false swapped for this - should also affect lock and state
it is a confic fix so isy needs to be rebooted to take effect after installing latest

**Comment by tritip** [comment]
Thanks, seems to be working properly now.
